### ISSUE TITLE
HSL and HSV lack conversion ability

### ISSUE THREAD

**Issue by joukewitteveen** [coloria-dev/colorio#188]
The HSL and HSV colorspaces do not have `from_xyz100(xyz)` and `to_xyz100(vals)` methods defined on them and can therefore not be used in conversions. Was this intentional?

**Comment by nschloe** [comment]
As opposed to most other color spaces, those are defined in terms of RGB, not XYZ which is why this came to pass. A conversion would be useful, I agree.

**Comment by nschloe** [comment]
This is fixed now. Will release later tonight.
