### ISSUE TITLE
Divide-by-zero in cs.HSL().from_rgb1()

### ISSUE THREAD

**Issue by toaarnio** [coloria-dev/colorio#205]
There's a floating-point underflow/rounding error in RGB-to-HSL conversion:

```
>>> colorio.cs.HSL().from_rgb1([1e-17, 0, 0])
<string>:38: RuntimeWarning: divide by zero encountered in true_divide
array([0.e+00,    inf, 5.e-18])
>>> colorio.cs.HSL().from_rgb1([1e-16, 0, 0])
array([0.00000000e+00, 9.00719925e-01, 5.00000000e-17])
```

Probable cause: At float64 precision, `(1.0 - 1e-17) == 1.0` is True, whereas `(1.0 - 1e-16) == 1.0` is False.

Possible workaround: mask out not only zeros but also near-zeros before dividing.

**Comment by nschloe** [comment]
Fixed now, will release later tonight.
